# Generated by Django 4.2.5 on 2023-10-03 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('estado_solicitud', models.CharField(choices=[('A', 'Aprobado'), ('P', 'Pendiente'), ('R', 'Rechazado')], default='P', max_length=1)),
                ('cantidad_solicitada', models.IntegerField()),
                ('producto_solicitado', models.CharField(choices=[('alarma', 'Alarma'), ('boton', 'Botón'), ('camaras', 'Cámaras')], max_length=10)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado')),
            ],
        ),
    ]
