# Generated by Django 4.2.4 on 2023-10-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('estado_solicitud', models.CharField(choices=[('A', 'Aprobado'), ('P', 'Pendiente'), ('R', 'Rechazado')], default='P', max_length=1)),
                ('cantidad_solicitada', models.IntegerField()),
                ('producto_solicitado', models.CharField(choices=[('alarma', 'Alarma'), ('boton', 'Botón'), ('camaras', 'Cámaras')], max_length=10)),
            ],
        ),
    ]
