# Generated by Django 4.2.5 on 2023-10-03 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
        ('solicitud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='empleado',
            field=models.ForeignKey(db_column='empleado_id_empleado', on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado'),
        ),
    ]
