# Generated by Django 4.2.5 on 2023-10-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(choices=[('alarma', 'Alarma'), ('boton', 'Botón'), ('camaras', 'Cámaras')], max_length=10, unique=True)),
                ('cantidad', models.PositiveIntegerField(default=200)),
            ],
        ),
    ]
